[package]
name = "ws_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
env_logger = "0.11.1"
log = "0.4.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
toml = "0.8"
tokio-native-tls = "0.3"
native-tls = "0.2"
sha1 = "0.10.6"
base64 = "0.21.7"
hmac = "0.12.1"
regex = "1.10.3"
simplelog = "0.12"
libc = "0.2.171"
nix = "0.26"
rand = "0.8.5"
getrandom = "0.2"
uuid = { version = "1.7", features = ["v4"] }
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1.88"
anyhow = "1.0.98"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
tungstenite = "0.21.0"

[dev-dependencies]
tempfile = "3.8"
