[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"

[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED", 
    "RUSTFLAGS",
    "PKG_CONFIG_ALLOW_CROSS",
    "FONTCONFIG_NO_PKG_CONFIG",
    "RUST_FONTCONFIG_DLOPEN",
    "FONTCONFIG_STATIC"
] 