name: Build Linux Binaries with Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: false
        default: 'latest'

jobs:
  build-linux-musl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.build -t nettest-builder .
        
    - name: Run builds in Docker
      run: |
        docker run --rm -v $(pwd):/app -w /app nettest-builder /usr/local/bin/build.sh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nettest-linux-musl-binaries
        path: |
          package/*.tar.gz
        retention-days: 30
        
    - name: Create latest release
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Nettest Latest Release (musl)
        files: package/*.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: false 