name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      create_release:
        description: 'Create GitHub Release'
        required: false
        type: boolean
        default: true

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libfontconfig1-dev
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-x86_64-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build for Linux x86_64
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        
    - name: Create package directory
      run: |
        mkdir -p package/nettest-${{ github.event.inputs.version }}-linux-x86_64
        
    - name: Copy binary
      run: |
        cp target/x86_64-unknown-linux-gnu/release/nettest package/nettest-${{ github.event.inputs.version }}-linux-x86_64/
        
    - name: Create README for package
      run: |
        cat > package/nettest-${{ github.event.inputs.version }}-linux-x86_64/README.txt << 'EOF'
        Nettest - Network Speed Measurement Tool
        
        Version: ${{ github.event.inputs.version }}
        Architecture: x86_64
        Build Date: $(date)
        
        Installation:
        1. Make binary executable: chmod +x nettest
        2. Run: ./nettest -s (server) or ./nettest -c <address> (client)
        
        For more information, visit: https://github.com/specure/nettest
        EOF
        
    - name: Create archive
      run: |
        cd package
        tar -czf nettest-${{ github.event.inputs.version }}-linux-x86_64.tar.gz nettest-${{ github.event.inputs.version }}-linux-x86_64/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nettest-${{ github.event.inputs.version }}-linux-x86_64
        path: package/nettest-${{ github.event.inputs.version }}-linux-x86_64.tar.gz

  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libfontconfig1-dev
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-arm64-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build for Linux ARM64
      run: |
        cargo build --release
        
    - name: Create package directory
      run: |
        mkdir -p package/nettest-${{ github.event.inputs.version }}-linux-aarch64
        
    - name: Copy binary
      run: |
        cp target/release/nettest package/nettest-${{ github.event.inputs.version }}-linux-aarch64/
        
    - name: Create README for package
      run: |
        cat > package/nettest-${{ github.event.inputs.version }}-linux-aarch64/README.txt << 'EOF'
        Nettest - Network Speed Measurement Tool
        
        Version: ${{ github.event.inputs.version }}
        Architecture: aarch64
        Build Date: $(date)
        
        Installation:
        1. Make binary executable: chmod +x nettest
        2. Run: ./nettest -s (server) or ./nettest -c <address> (client)
        
        For more information, visit: https://github.com/specure/nettest
        EOF
        
    - name: Create archive
      run: |
        cd package
        tar -czf nettest-${{ github.event.inputs.version }}-linux-aarch64.tar.gz nettest-${{ github.event.inputs.version }}-linux-aarch64/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nettest-${{ github.event.inputs.version }}-linux-aarch64
        path: package/nettest-${{ github.event.inputs.version }}-linux-aarch64.tar.gz

  create-release:
    needs: [build-x86_64, build-arm64]
    runs-on: ubuntu-latest
    if: github.event.inputs.create_release == 'true'
    permissions:
      contents: write
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        files: |
          nettest-${{ github.event.inputs.version }}-linux-x86_64/nettest-${{ github.event.inputs.version }}-linux-x86_64.tar.gz
          nettest-${{ github.event.inputs.version }}-linux-aarch64/nettest-${{ github.event.inputs.version }}-linux-aarch64.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 