name: Publish Packages

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libfontconfig1-dev
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build for Linux x86_64
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        
    - name: Create package directory
      run: |
        mkdir -p package/nettest-linux-x86_64
        
    - name: Copy binary
      run: |
        cp target/x86_64-unknown-linux-gnu/release/nettest package/nettest-linux-x86_64/
        
    - name: Create archive
      run: |
        cd package
        tar -czf nettest-linux-x86_64.tar.gz nettest-linux-x86_64/
        
    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: nettest-linux-x86_64
        path: package/nettest-linux-x86_64.tar.gz
        
    - name: Create Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: package/nettest-linux-x86_64.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libfontconfig1-dev
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-arm64-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build for Linux ARM64
      run: |
        cargo build --release
        
    - name: Create package directory
      run: |
        mkdir -p package/nettest-linux-aarch64
        
    - name: Copy binary
      run: |
        cp target/release/nettest package/nettest-linux-aarch64/
        
    - name: Create archive
      run: |
        cd package
        tar -czf nettest-linux-aarch64.tar.gz nettest-linux-aarch64/
        
    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: nettest-linux-aarch64
        path: package/nettest-linux-aarch64.tar.gz
        
    - name: Create Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: package/nettest-linux-aarch64.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 